jugadores=[{'Id jugador' : 'Pamela',
        'Nombre': 'Pamela',
        'Apellido': 'Alvarez',
        'Fornite': '1200',
        'Fifa': '1333',
        'Valorant': '3000',
        'Tipo': 'Experto',}, {'Id jugador' : 'id_jugador',
        'Nombre': 'nombre',
        'Apellido': 'apellido',
        'Fornite': 'fornite',
        'Fifa': 'fifa',
        'Valorant': 'valorant',
        'Tipo': 'tipo'},{'Id jugador' : 'id_jugador',
        'Nombre': 'nombre',
        'Apellido': 'apellido',
        'Fornite': 'fornite',
        'Fifa': 'fifa',
        'Valorant': 'valorant',
        'Tipo': 'tipo'}]
print(f'')
